# Generated by Django 3.0.6 on 2020-05-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-category']},
        ),
    ]
